### ISSUE TITLE
openvpnauth.sh: line 81: mkpasswd: command not found

### ISSUE THREAD

**Issue by powermx** [carlrygart/OpenVPNAuth#1]
Error creating NEW USER

**Comment by carlrygart** [comment]
I guess you're using macOS? This script works fine on operating systems with mkpasswd inbuilt, i.e. Debian/Ubuntu. Feel free to make it work on macOS if you want to.

**Comment by powermx** [comment]
Hello, thx for answer, I'm using Ubuntu 18.04 x64 from digitalocean

**Comment by carlrygart** [comment]
Weird, I thought it was included in Ubuntu by default, apparently not. However, mkpasswd is a utility of the whois package. So try to install whois. I will update the readme.
